// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTBSHTceEYGRCo1MzjyFAtATMApn0n-Q0',
    appId: '1:854183847021:web:1c08ab408aebc3f8574b64',
    messagingSenderId: '854183847021',
    projectId: 'internconnect-1db1f',
    authDomain: 'internconnect-1db1f.firebaseapp.com',
    storageBucket: 'internconnect-1db1f.firebasestorage.app',
    measurementId: 'G-LEPRK77CFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbteSboTUoQVjS6OfDKcu1YhMzKvaZfI4',
    appId: '1:854183847021:android:57e297e1bf4aa81c574b64',
    messagingSenderId: '854183847021',
    projectId: 'internconnect-1db1f',
    storageBucket: 'internconnect-1db1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBviNlOQlogtfznGJx95B75Ud1p7rGL_C4',
    appId: '1:854183847021:ios:776f8349f59c9cf1574b64',
    messagingSenderId: '854183847021',
    projectId: 'internconnect-1db1f',
    storageBucket: 'internconnect-1db1f.firebasestorage.app',
    iosBundleId: 'com.example.internConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBviNlOQlogtfznGJx95B75Ud1p7rGL_C4',
    appId: '1:854183847021:ios:776f8349f59c9cf1574b64',
    messagingSenderId: '854183847021',
    projectId: 'internconnect-1db1f',
    storageBucket: 'internconnect-1db1f.firebasestorage.app',
    iosBundleId: 'com.example.internConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTBSHTceEYGRCo1MzjyFAtATMApn0n-Q0',
    appId: '1:854183847021:web:081d3df50a73ceb9574b64',
    messagingSenderId: '854183847021',
    projectId: 'internconnect-1db1f',
    authDomain: 'internconnect-1db1f.firebaseapp.com',
    storageBucket: 'internconnect-1db1f.firebasestorage.app',
    measurementId: 'G-J5J377B3X1',
  );
}
